# Generated by maven-r-jsr223-plugin: do not edit by hand
# a java class R6 wrapper
AnotherTestRApi = R6::R6Class("AnotherTestRApi", public=list(
	.api = NULL,
	.jobj = NULL,
	.ptr = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
		self$.ptr = xptr::xptr_address(jobj@jobj)
		api$register(self)
	},
	
	throwCatchable = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwCatchable" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	printMessage = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="printMessage" ); 
		# convert java object back to R
		return(self$.api$.fromJava$void(tmp_out));
	},
	throwRuntime = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwRuntime" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		print(tmp_out)
		invisible(self)
	}
))
