# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A test library
#' R6 Bindings for Java BounceTest
#'
#' @description
#' missing description
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.02
#' 
#' Generated: 2022-02-16T15:04:09.226
#'
#' @details
	#' no details
#' @export
BounceTest = R6::R6Class("BounceTest", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new BounceTest this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new BounceTest object.
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' instance = J$BounceTest$new()
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' bounceNull: 
	#' no description
	#' @param x - (java expects a RNull)
	#' @return RNull: 
	#' 
	bounceNull = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNull(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNull;", method="bounceNull" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RNull(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceVoid: 
	#' no description
	#' @return void: 
	#' 
	bounceVoid = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="bounceVoid" ); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceString: 
	#' no description
	#' @param x - (java expects a String)
	#' @return String: 
	#' 
	bounceString = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$String(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="bounceString" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$String(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceCharacter: 
	#' no description
	#' @param x - (java expects a RCharacter)
	#' @return RCharacter: 
	#' 
	bounceCharacter = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RCharacter(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="bounceCharacter" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceCharacterVector: 
	#' no description
	#' @param x - (java expects a RCharacterVector)
	#' @return RCharacterVector: 
	#' 
	bounceCharacterVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RCharacterVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="bounceCharacterVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceDouble: 
	#' no description
	#' @param x - (java expects a double)
	#' @return double: 
	#' 
	bounceDouble = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$double(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "D", method="bounceDouble" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$double(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceNumeric: 
	#' no description
	#' @param x - (java expects a RNumeric)
	#' @return RNumeric: 
	#' 
	bounceNumeric = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNumeric(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="bounceNumeric" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumeric(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceNumericVector: 
	#' no description
	#' @param x - (java expects a RNumericVector)
	#' @return RNumericVector: 
	#' 
	bounceNumericVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNumericVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericVector;", method="bounceNumericVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumericVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceInt: 
	#' no description
	#' @param x - (java expects a int)
	#' @return int: 
	#' 
	bounceInt = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$int(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "I", method="bounceInt" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$int(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceInteger: 
	#' no description
	#' @param x - (java expects a RInteger)
	#' @return RInteger: 
	#' 
	bounceInteger = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RInteger(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RInteger;", method="bounceInteger" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RInteger(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceIntegerVector: 
	#' no description
	#' @param x - (java expects a RIntegerVector)
	#' @return RIntegerVector: 
	#' 
	bounceIntegerVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RIntegerVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RIntegerVector;", method="bounceIntegerVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RIntegerVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceFactor: 
	#' no description
	#' @param x - (java expects a RFactor)
	#' @return RFactor: 
	#' 
	bounceFactor = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RFactor(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactor;", method="bounceFactor" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactor(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceFactorVector: 
	#' no description
	#' @param x - (java expects a RFactorVector)
	#' @return RFactorVector: 
	#' 
	bounceFactorVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RFactorVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactorVector;", method="bounceFactorVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactorVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceDate: 
	#' no description
	#' @param x - (java expects a RDate)
	#' @return RDate: 
	#' 
	bounceDate = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDate(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDate;", method="bounceDate" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RDate(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceDateVector: 
	#' no description
	#' @param x - (java expects a RDateVector)
	#' @return RDateVector: 
	#' 
	bounceDateVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDateVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDateVector;", method="bounceDateVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RDateVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceLogical: 
	#' no description
	#' @param x - (java expects a RLogical)
	#' @return RLogical: 
	#' 
	bounceLogical = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RLogical(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogical;", method="bounceLogical" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogical(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceLogicalVector: 
	#' no description
	#' @param x - (java expects a RLogicalVector)
	#' @return RLogicalVector: 
	#' 
	bounceLogicalVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RLogicalVector(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogicalVector;", method="bounceLogicalVector" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogicalVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceDataframe: 
	#' no description
	#' @param x - (java expects a RDataframe)
	#' @return RDataframe: 
	#' 
	bounceDataframe = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDataframe(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="bounceDataframe" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceList: 
	#' no description
	#' @param x - (java expects a RList)
	#' @return RList: 
	#' 
	bounceList = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RList(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RList;", method="bounceList" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceNamedList: 
	#' no description
	#' @param x - (java expects a RNamedList)
	#' @return RNamedList: 
	#' 
	bounceNamedList = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNamedList(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="bounceNamedList" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RNamedList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' bounceArray: 
	#' no description
	#' @param x - (java expects a RNumericArray)
	#' @return RNumericArray: 
	#' 
	bounceArray = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNumericArray(x);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericArray;", method="bounceArray" , tmp_x); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumericArray(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this BounceTest
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this BounceTest
	#' @param object The R6 instance to test for equality to this BounceTest  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		
		self$.jobj = .jnull("uk/co/terminological/rjava/test/BounceTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
