# Generated by maven-r-jsr223-plugin: do not edit by hand
# a java class R6 wrapper
BounceTest = R6::R6Class("BounceTest", public=list(
	.api = NULL,
	.jobj = NULL,
	.ptr = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
		self$.ptr = xptr::xptr_address(jobj@jobj)
		api$register(self)
	},
	
	bounceVoid = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="bounceVoid" ); 
		# convert java object back to R
		return(self$.api$.fromJava$void(tmp_out));
	},
	bounceInt = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$int(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "I", method="bounceInt" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$int(tmp_out));
	},
	bounceDouble = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$double(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "D", method="bounceDouble" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$double(tmp_out));
	},
	bounceString = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$String(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="bounceString" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$String(tmp_out));
	},
	bounceNull = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNull(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNull;", method="bounceNull" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RNull(tmp_out));
	},
	bounceCharacter = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RCharacter(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="bounceCharacter" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	bounceCharacterVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RCharacterVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="bounceCharacterVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacterVector(tmp_out));
	},
	bounceInteger = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RInteger(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RInteger;", method="bounceInteger" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RInteger(tmp_out));
	},
	bounceIntegerVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RIntegerVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RIntegerVector;", method="bounceIntegerVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RIntegerVector(tmp_out));
	},
	bounceDate = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDate(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDate;", method="bounceDate" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RDate(tmp_out));
	},
	bounceDateVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDateVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDateVector;", method="bounceDateVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RDateVector(tmp_out));
	},
	bounceFactor = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RFactor(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactor;", method="bounceFactor" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RFactor(tmp_out));
	},
	bounceFactorVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RFactorVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactorVector;", method="bounceFactorVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RFactorVector(tmp_out));
	},
	bounceLogical = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RLogical(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogical;", method="bounceLogical" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RLogical(tmp_out));
	},
	bounceLogicalVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RLogicalVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogicalVector;", method="bounceLogicalVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RLogicalVector(tmp_out));
	},
	bounceNumeric = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNumeric(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="bounceNumeric" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RNumeric(tmp_out));
	},
	bounceNumericVector = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNumericVector(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericVector;", method="bounceNumericVector" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RNumericVector(tmp_out));
	},
	bounceDataframe = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RDataframe(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="bounceDataframe" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RDataframe(tmp_out));
	},
	bounceList = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RList(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RList;", method="bounceList" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RList(tmp_out));
	},
	bounceNamedList = function(x) {
		# copy parameters
		tmp_x = self$.api$.toJava$RNamedList(x);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="bounceNamedList" , tmp_x); 
		# convert java object back to R
		return(self$.api$.fromJava$RNamedList(tmp_out));
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		print(tmp_out)
		invisible(self)
	}
))
