# Generated by maven-r-jsr223-plugin: do not edit by hand
# a java class R6 wrapper
DataframeSerialiser = R6::R6Class("DataframeSerialiser", public=list(
	.api = NULL,
	.jobj = NULL,
	.ptr = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
		self$.ptr = xptr::xptr_address(jobj@jobj)
		api$register(self)
	},
	
	serialise = function(dataframe, filename) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		tmp_filename = self$.api$.toJava$String(filename);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="serialise" , tmp_dataframe, tmp_filename); 
		# convert java object back to R
		return(self$.api$.fromJava$void(tmp_out));
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		print(tmp_out)
		invisible(self)
	}
))
