# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the testRapi generated R library.
#
# A test library
# Version: 0.02
# Generated: 2021-06-18T23:43:44.613
# Contact: rc538@exeter.ac.uk
FactoryTest = R6::R6Class("FactoryTest", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	generateCharacter = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="generateCharacter" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateNumeric = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="generateNumeric" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumeric(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateInteger = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RInteger;", method="generateInteger" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RInteger(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateFactor = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactor;", method="generateFactor" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactor(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateLogical = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogical;", method="generateLogical" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogical(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateCharacterVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="generateCharacterVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateNumericVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericVector;", method="generateNumericVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumericVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateIntegerVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RIntegerVector;", method="generateIntegerVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RIntegerVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateFactorVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactorVector;", method="generateFactorVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactorVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateLogicalVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogicalVector;", method="generateLogicalVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogicalVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateDataframe = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataframe" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateStreamDataframe = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateStreamDataframe" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateList = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RList;", method="generateList" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateNamedList = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="generateNamedList" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNamedList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/FactoryTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
