# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A test library
#' R6 Bindings for Java FactoryTest
#'
#' @description
#' missing description
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.02
#' 
#' Generated: 2022-04-26T13:20:40.813
#'
#' @details
	#' no details
#' @export
FactoryTest = R6::R6Class("FactoryTest", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new FactoryTest this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new FactoryTest object.
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' instance = J$FactoryTest$new()
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' generateCharacter: 
	#' no description
	#' @return RCharacter: 
	#' 
	generateCharacter = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="generateCharacter" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateNumeric: 
	#' no description
	#' @return RNumeric: 
	#' 
	generateNumeric = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="generateNumeric" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumeric(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateInteger: 
	#' no description
	#' @return RInteger: 
	#' 
	generateInteger = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RInteger;", method="generateInteger" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RInteger(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateFactor: 
	#' no description
	#' @return RFactor: 
	#' 
	generateFactor = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactor;", method="generateFactor" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactor(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateLogical: 
	#' no description
	#' @return RLogical: 
	#' 
	generateLogical = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogical;", method="generateLogical" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogical(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateCharacterVec: 
	#' no description
	#' @return RCharacterVector: 
	#' 
	generateCharacterVec = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="generateCharacterVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateNumericVec: 
	#' no description
	#' @return RNumericVector: 
	#' 
	generateNumericVec = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericVector;", method="generateNumericVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumericVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateIntegerVec: 
	#' no description
	#' @return RIntegerVector: 
	#' 
	generateIntegerVec = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RIntegerVector;", method="generateIntegerVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RIntegerVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateFactorVec: 
	#' no description
	#' @return RFactorVector: 
	#' 
	generateFactorVec = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactorVector;", method="generateFactorVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RFactorVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateLogicalVec: 
	#' no description
	#' @return RLogicalVector: 
	#' 
	generateLogicalVec = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogicalVector;", method="generateLogicalVec" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RLogicalVector(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateDataframe: 
	#' no description
	#' @return RDataframe: 
	#' 
	generateDataframe = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataframe" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateStreamDataframe: 
	#' no description
	#' @return RDataframe: 
	#' 
	generateStreamDataframe = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateStreamDataframe" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateList: 
	#' Lists are much harder to type check than vectors hence RList builder methods throw checked exceptions
	#' @return RList: 
	#' a RList containing the supplied Java objects converted into RObjects
	generateList = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RList;", method="generateList" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateNamedList: 
	#' no description
	#' @return RNamedList: 
	#' 
	generateNamedList = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="generateNamedList" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RNamedList(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this FactoryTest
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this FactoryTest
	#' @param object The R6 instance to test for equality to this FactoryTest  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/FactoryTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
