# Generated by maven-r-jsr223-plugin: do not edit by hand
# a java class R6 wrapper
FactoryTest = R6::R6Class("FactoryTest", public=list(
	.api = NULL,
	.jobj = NULL,
	.ptr = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
		self$.ptr = xptr::xptr_address(jobj@jobj)
		api$register(self)
	},
	
	generateCharacter = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="generateCharacter" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	generateNumeric = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="generateNumeric" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RNumeric(tmp_out));
	},
	generateInteger = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RInteger;", method="generateInteger" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RInteger(tmp_out));
	},
	generateFactor = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactor;", method="generateFactor" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RFactor(tmp_out));
	},
	generateLogical = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogical;", method="generateLogical" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RLogical(tmp_out));
	},
	generateCharacterVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="generateCharacterVec" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacterVector(tmp_out));
	},
	generateNumericVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumericVector;", method="generateNumericVec" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RNumericVector(tmp_out));
	},
	generateIntegerVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RIntegerVector;", method="generateIntegerVec" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RIntegerVector(tmp_out));
	},
	generateFactorVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RFactorVector;", method="generateFactorVec" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RFactorVector(tmp_out));
	},
	generateLogicalVec = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RLogicalVector;", method="generateLogicalVec" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RLogicalVector(tmp_out));
	},
	generateDataframe = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataframe" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RDataframe(tmp_out));
	},
	generateStreamDataFrame = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateStreamDataFrame" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RDataframe(tmp_out));
	},
	generateList = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RList;", method="generateList" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RList(tmp_out));
	},
	generateNamedList = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="generateNamedList" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RNamedList(tmp_out));
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		print(tmp_out)
		invisible(self)
	}
))
