# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the testRapi generated R library.
#
# A test library
# Version: 0.02
# Generated: 2021-06-18T23:43:44.609
# Contact: rc538@exeter.ac.uk
FeatureTest = R6::R6Class("FeatureTest", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	doHelloWorld = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="doHelloWorld" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	doSum = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$RNumeric(a);
		tmp_b = self$.api$.toJava$RNumeric(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="doSum" , tmp_a, tmp_b); 
		# convert java object back to R
		out = self$.api$.fromJava$RNumeric(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	doSum2 = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$int(a);
		tmp_b = self$.api$.toJava$int(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "I", method="doSum2" , tmp_a, tmp_b); 
		# convert java object back to R
		out = self$.api$.fromJava$int(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	getMessage = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="getMessage" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	fluentSetMessage = function(message) {
		# copy parameters
		tmp_message = self$.api$.toJava$RCharacter(message);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/test/FeatureTest;", method="fluentSetMessage" , tmp_message); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = FeatureTest$new(
				self$.api$.fromJava$FeatureTest(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	factoryMethod = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$RCharacter(a);
		tmp_b = self$.api$.toJava$RCharacter(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/test/MoreFeatureTest;", method="factoryMethod" , tmp_a, tmp_b); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = MoreFeatureTest$new(
				self$.api$.fromJava$MoreFeatureTest(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	objectAsParameter = function(otherObj) {
		# copy parameters
		tmp_otherObj = self$.api$.toJava$MoreFeatureTest(otherObj);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="objectAsParameter" , tmp_otherObj); 
		# convert java object back to R
		out = self$.api$.fromJava$String(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	doSomethingWithDataFrame = function(dataframe) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="doSomethingWithDataFrame" , tmp_dataframe); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	generateDataFrame = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataFrame" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/FeatureTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
