# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A test library
#' R6 Bindings for Java FeatureTest
#'
#' @description
#' A test of the R6 generator templating
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.2.0.9000
#' 
#' Generated: 2022-05-23T17:14:54.557495
#'
#' @details
	#' The feature test should allow mathjax in javadoc
	#' 
	#' $$e = mc^2$$
	#' 
	#' 
	#' this is a details comment
#' @export
FeatureTest = R6::R6Class("FeatureTest", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new FeatureTest this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new FeatureTest object.
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' instance = J$FeatureTest$new(logMessage)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' doHelloWorld: 
	#' Description of a hello world function
	#' @return RCharacter: 
	#' this java method returns a String
	#' @examples
	#' \dontrun{
	#' minExample = J$FeatureTest$new('Hello, R World!')
	#' minExample$doHelloWorld()
	#' }
	doHelloWorld = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="doHelloWorld" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' doSum: 
	#' The doSum function description = it adds two numerics
	#' @param a the A parameter, can be NA - (java expects a RNumeric)
	#' @param b the B parameter - (java expects a RNumeric)
	#' @return RNumeric: 
	#' A+B of course, NAs in inputs are converted to null in Java. This catches the resulting NPE in java idiom and returns an explicit NA. 
	#' This only matters if you care about the difference between NA_real_ and NaN in R.
	doSum = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$RNumeric(a);
		tmp_b = self$.api$.toJava$RNumeric(b);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="doSum" , tmp_a, tmp_b, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RNumeric(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' doSum2: 
	#' Do sum 2 uses native ints rather than RNumerics
	#' It should throw an error if given something that cannot be coerced to an integer. 
	#' This also demonstrated the use of the `@RDefault` annotation
	#' @param a the A parameter - (java expects a int)
	#' @param b the B parameter - (defaulting to 10) - (java expects a int)
	#' @return int: 
	#' A+B of course
	doSum2 = function(a, b=10) {
		# copy parameters
		tmp_a = self$.api$.toJava$int(a);
		tmp_b = self$.api$.toJava$int(b);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "I", method="doSum2" , tmp_a, tmp_b, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$int(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' getMessage: 
	#' message desciption
	#' @return RCharacter: 
	#' The message (previously set by the constructor)
	getMessage = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="getMessage" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' fluentSetMessage: 
	#' A fluent method which updates the message in this object, returning the
	#' same object. This is differentiated from factory methods which produce a new
	#' instance of the same class by checking to see if the returned Java object is equal
	#' to the calling Java object.
	#' @param message the message is a string - (defaulting to \\"hello\\nworld\\") - (java expects a RCharacter)
	#' @return R6 FeatureTest object: 
	#' this should return exactly the same R6 object.
	fluentSetMessage = function(message="hello
world") {
		# copy parameters
		tmp_message = self$.api$.toJava$RCharacter(message);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/test/FeatureTest;", method="fluentSetMessage" , tmp_message, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = FeatureTest$new(
				self$.api$.fromJava$FeatureTest(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' factoryMethod: 
	#' A factory or builder method which constructs an object of another class from some parameters
	#' @param a the first parameter - (java expects a RCharacter)
	#' @param b the second parameter - (defaulting to as.character(Sys.Date())) - (java expects a RCharacter)
	#' @return R6 MoreFeatureTest object: 
	#' A MoreFeatureTest R6 reference
	factoryMethod = function(a, b=as.character(Sys.Date())) {
		# copy parameters
		tmp_a = self$.api$.toJava$RCharacter(a);
		tmp_b = self$.api$.toJava$RCharacter(b);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/test/MoreFeatureTest;", method="factoryMethod" , tmp_a, tmp_b, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = MoreFeatureTest$new(
				self$.api$.fromJava$MoreFeatureTest(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' objectAsParameter: 
	#' no description
	#' @param otherObj - (java expects a MoreFeatureTest)
	#' @return String: 
	#' 
	objectAsParameter = function(otherObj) {
		# copy parameters
		tmp_otherObj = self$.api$.toJava$MoreFeatureTest(otherObj);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="objectAsParameter" , tmp_otherObj, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$String(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' doSomethingWithDataFrame: 
	#' Consumes a data frame and logs its length
	#' @param dataframe a dataframe - (java expects a RDataframe)
	#' @return void: 
	#' 
	doSomethingWithDataFrame = function(dataframe) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="doSomethingWithDataFrame" , tmp_dataframe, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' generateDataFrame: 
	#' Creates a basic dataframe and returns it
	#' @return RDataframe: 
	#' a daatframe
	generateDataFrame = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataFrame" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' errorThrower: 
	#' just throws an error
	#' @return void: 
	#' 
	errorThrower = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="errorThrower" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this FeatureTest
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this FeatureTest
	#' @param object The R6 instance to test for equality to this FeatureTest  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		if(!is.null(self$.jobj)) {
			.jcall(self$.jobj, returnSig = "V", method="close", check=FALSE)
			e = .jgetEx(clear=TRUE)
			if (!is.null(e)) {
				self$.api$.log$error(e$getMessage())
			}
			self$.api$printMessages() 
		}
		self$.jobj = .jnull("uk/co/terminological/rjava/test/FeatureTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
