# Generated by maven-r-jsr223-plugin: do not edit by hand
# a java class R6 wrapper
FeatureTest = R6::R6Class("FeatureTest", public=list(
	.api = NULL,
	.jobj = NULL,
	.ptr = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
		self$.ptr = xptr::xptr_address(jobj@jobj)
		api$register(self)
	},
	
	doHelloWorld = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="doHelloWorld" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	fluentSetMessage = function(message) {
		# copy parameters
		tmp_message = self$.api$.toJava$RCharacter(message);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/mavenrjsr233plugintest/FeatureTest;", method="fluentSetMessage" , tmp_message); 
		# get object if it already exists
		if(self$.api$isRegistered(tmp_out)) return(self$.api$getRegistered(tmp_out))
		# wrap return java object in R6 class  
		return(FeatureTest$new(
			self$.api$.fromJava$FeatureTest(tmp_out),
			self$.api
		));
	},
	factoryMethod = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$RCharacter(a);
		tmp_b = self$.api$.toJava$RCharacter(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/mavenrjsr233plugintest/MoreFeatureTest;", method="factoryMethod" , tmp_a, tmp_b); 
		# get object if it already exists
		if(self$.api$isRegistered(tmp_out)) return(self$.api$getRegistered(tmp_out))
		# wrap return java object in R6 class  
		return(MoreFeatureTest$new(
			self$.api$.fromJava$MoreFeatureTest(tmp_out),
			self$.api
		));
	},
	getMessage = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="getMessage" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RCharacter(tmp_out));
	},
	doSum = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$RNumeric(a);
		tmp_b = self$.api$.toJava$RNumeric(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNumeric;", method="doSum" , tmp_a, tmp_b); 
		# convert java object back to R
		return(self$.api$.fromJava$RNumeric(tmp_out));
	},
	doSum2 = function(a, b) {
		# copy parameters
		tmp_a = self$.api$.toJava$int(a);
		tmp_b = self$.api$.toJava$int(b);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "I", method="doSum2" , tmp_a, tmp_b); 
		# convert java object back to R
		return(self$.api$.fromJava$int(tmp_out));
	},
	objectAsParameter = function(otherObj) {
		# copy parameters
		tmp_otherObj = self$.api$.toJava$MoreFeatureTest(otherObj);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="objectAsParameter" , tmp_otherObj); 
		# convert java object back to R
		return(self$.api$.fromJava$String(tmp_out));
	},
	doSomethingWithDataFrame = function(dataframe) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="doSomethingWithDataFrame" , tmp_dataframe); 
		# convert java object back to R
		return(self$.api$.fromJava$void(tmp_out));
	},
	generateDataFrame = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="generateDataFrame" ); 
		# convert java object back to R
		return(self$.api$.fromJava$RDataframe(tmp_out));
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		print(tmp_out)
		invisible(self)
	}
))
