# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a java class in a jsr223 engine
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	.log = NULL,
	.fromJava = NULL,
	.toJava = NULL,
	.reg = list(),
	TestRApi = NULL,
	BounceTest = NULL,
	FactoryTest = NULL,
	AnotherTestRApi = NULL,
  
  	changeLogLevel = function(logLevel) {
  		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "changeLogLevel" , logLevel)
    },
	
	reconfigureLog = function(log4jproperties) {
  		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "reconfigureLog" , log4jproperties)
    },
	
	#### registration functions
	
	register = function(r6obj) {
		ptr = xptr::xptr_address(r6obj$.jobj@jobj)
		self$.reg[[ptr]] = r6obj
	},
	
	isRegistered = function(jobj) {
		ptr = xptr::xptr_address(jobj@jobj)
		return(!is.null(self$.reg[[ptr]]))
	},
	
	getRegistered = function(jobj) {
		ptr = xptr::xptr_address(jobj@jobj)
		return(self$.reg[[ptr]])
	},
	
 	#### constructor ----
 	initialize = function(logLevel = "INFO") {
 	
 		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "configureLog" , logLevel)
    	self$.log = .jcall("org/slf4j/LoggerFactory", returnSig = "Lorg/slf4j/Logger;", method = "getLogger", "testRapi");
		.jcall(self$.log,returnSig = "V",method = "info","testRapi: JavaApi initialised");
	
		# initialise type conversion functions
		
		self$.toJava = list(
			FactoryTest=function(rObj) return(rObj),
			void=function(rObj) stop('no input expected'),
			RDateVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RDateVector'))
				tmp = as.character(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDateVector',rJava::.jarray(tmp)))
			},
			RDate=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RDate'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.character(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDate',tmp))
			},
			AnotherTestRApi=function(rObj) return(rObj),
			double=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java double')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.numeric(rObj)) stop('not an double')
			    return(as.numeric(rObj[[1]]))
			},
			RList=function(rObj) {
			   if (!is.list(rObj)) stop ('expecting a list ')
			   if (!is.null(names(rObj))) warning('not expecting list to be named')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RList')
				lapply(rObj, function(x) {
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Z',method='add',rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			},
			TestRApi=function(rObj) return(rObj),
			RCharacterVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector'))
				if (!is.character(rObj)) stop('expected a vector of characters')
				tmp = as.character(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector',rJava::.jarray(tmp)))
			},
			RNumericVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector',rJava::.jarray(tmp)))
			},
			RNumeric=function(rObj) {
				if (length(rObj) > 1) stop('input too long')
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumeric',tmp))
			},
			RLogical=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical'))
				if (length(rObj) > 1) stop('input too long')
				if (!is.logical(rObj)) stop('expected a logical')
				tmp = as.integer(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical',tmp))
			},
			RFactor=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				tmpLabel = levels(rObj)[[tmp]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor',tmp, tmpLabel))
			},
			int=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java int')
			    if (length(rObj) > 1) stop('input too long')
			    if (as.integer(rObj)[[1]]!=rObj[[1]]) stop('not an integer')
			    return(as.integer(rObj[[1]]))
			},
			RLogicalVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector'))
				if (!is.logical(rObj)) stop('expected a vector of logicals')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector',rJava::.jarray(tmp)))
			},
			RCharacter=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter'))
				tmp = as.character(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter',tmp))
			},
			RNull=function(rObj) {
				if (!is.null(rObj)) stop('input expected to be NULL')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNull'))
			},
			RInteger=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				if (rObj[[1]]!=tmp) stop('cannot cast to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger',tmp))
			},
			RDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				return(jout)
			},
			BounceTest=function(rObj) return(rObj),
			String=function(rObj) return(as.character(rObj)),
			RFactorVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector'))
				if (!is.factor(rObj)) stop('expected a vector of factors')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector', rJava::.jarray(tmp), rJava::.jarray(levels(rObj))))
			},
			RIntegerVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector'))
				tmp = as.integer(rObj)
				if (any(rObj!=tmp,na.rm=TRUE)) stop('cannot coerce to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector',rJava::.jarray(tmp)))
			},
			RNamedList=function(rObj) {
				if (!is.list(rObj) | is.null(names(rObj))) stop ('expecting a named list')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RNamedList')
				lapply(names(rObj), function(name) {
					x = rObj[[name]]
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RObject;',method='put',name,rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			}		)
		
		self$.fromJava = list(
			FactoryTest=function(jObj) return(jObj),
			void=function(jObj) return(NULL),
			RDateVector=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RDate=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			AnotherTestRApi=function(jObj) return(jObj),
			double=function(jObj) return(as.numeric(jObj)),
			RList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			},
			TestRApi=function(jObj) return(jObj),
			RCharacterVector=function(jObj) as.character(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive')),
			RNumericVector=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive')),
			RNumeric=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='D',method='rPrimitive')),
			RLogical=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RFactor=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rLabel')),
			int=function(jObj) return(as.integer(jObj)),
			RLogicalVector=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RCharacter=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive')),
			RNull=function(jObj) return(NULL),
			RInteger=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				return(convDf(jObj))
			},
			BounceTest=function(jObj) return(jObj),
			String=function(jObj) return(as.character(jObj)),
			RFactorVector=function(jObj) ordered(
				x = rJava::.jcall(jObj,returnSig='[I',method='rValues'),
				labels = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rLevels')
			),
			RIntegerVector=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RNamedList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			}		)
	
		# initialise java class constructors and static method definitions
		
		self$TestRApi = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/mavenrjsr233plugintest/TestRApi" ); 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = TestRApi$new(
					self$.fromJava$TestRApi(tmp_out),
					self
				);
			}
	)
		self$BounceTest = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/mavenrjsr233plugintest/BounceTest" ); 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = BounceTest$new(
					self$.fromJava$BounceTest(tmp_out),
					self
				);
			}
	)
		self$FactoryTest = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/mavenrjsr233plugintest/FactoryTest" ); 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = FactoryTest$new(
					self$.fromJava$FactoryTest(tmp_out),
					self
				);
			}
	)
		self$AnotherTestRApi = list(
			new = function(message1, message2) {
				# constructor
				# convert parameters to java
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/mavenrjsr233plugintest/AnotherTestRApi" , tmp_message1, tmp_message2); 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = AnotherTestRApi$new(
					self$.fromJava$AnotherTestRApi(tmp_out),
					self
				);
			},
			create = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				#execute static call
				tmp_out = .jcall("uk/co/terminological/mavenrjsr233plugintest/AnotherTestRApi", returnSig = "Luk/co/terminological/mavenrjsr233plugintest/AnotherTestRApi;", method="create" , tmp_message1, tmp_message2); 
				# get object if it already exists
				if(self$isRegistered(tmp_out)) return(self$getRegistered(tmp_out))
				# wrap return java object in R6 class 
				return(AnotherTestRApi$new(
					self$.fromJava$AnotherTestRApi(tmp_out),
					self
				));
			},
			concat = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				#execute static call
				tmp_out = .jcall("uk/co/terminological/mavenrjsr233plugintest/AnotherTestRApi", returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="concat" , tmp_message1, tmp_message2); 
				# convert java object back to R
				return(self$.fromJava$RCharacter(tmp_out));
			}	)
	}
))

