# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A test library
#' R6 Bindings for Java MinimalExample
#'
#' @description
#' This class is a very basic example of the features of the rJava maven plugin. <br>
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.02
#' 
#' Generated: 2022-03-29T00:47:33.602
#'
#' @details
	#' #' The class is annotated with an @RClass to identify it as part of the R API. <br>
#' @export
MinimalExample = R6::R6Class("MinimalExample", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new MinimalExample this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new MinimalExample object.
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' instance = J$MinimalExample$new()
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' demo: 
	#' Documentation of the method can be done in JavaDoc and these will be present in the R documentation
	#' @param dataframe - a dataframe with an arbitrary number of columns - (java expects a RDataframe)
	#' @param message - a message - (java expects a String)
	#' @return RDataframe: 
	#' the dataframe unchanged
	#' @examples
	#' \dontrun{
	#' #' 		minExample = J$MinimalExample$new()
	#' minExample$demo(dataframe=tibble::tibble(input=c(1,2,3)), message='Hello world')
	#' }
	demo = function(dataframe, message) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		tmp_message = self$.api$.toJava$String(message);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="demo" , tmp_dataframe, tmp_message); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this MinimalExample
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this MinimalExample
	#' @param object The R6 instance to test for equality to this MinimalExample  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/MinimalExample")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
