# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the testRapi generated R library.
#
# A test library
# Version: 0.02
# Generated: 2021-12-22T09:37:35.997
# Contact: rc538@exeter.ac.uk
MinimalExample = R6::R6Class("MinimalExample", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	demo = function(dataframe, message) {
		# copy parameters
		tmp_dataframe = self$.api$.toJava$RDataframe(dataframe);
		tmp_message = self$.api$.toJava$String(message);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="demo" , tmp_dataframe, tmp_message); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/MinimalExample")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
