# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A test library
#' R6 Bindings for Java MoreFeatureTest
#'
#' @description
#' This has no documentation
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.02
#' 
#' Generated: 2022-03-29T00:47:33.506
#'
#' @details
	#' This has no documentation
#' @export
MoreFeatureTest = R6::R6Class("MoreFeatureTest", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new MoreFeatureTest this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new MoreFeatureTest object.
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' instance = J$MoreFeatureTest$new(message1, message2)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' testLogging: 
	#' no description
	#' @return void: 
	#' 
	testLogging = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="testLogging" ); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' throwCatchable: 
	#' no description
	#' @return RCharacter: 
	#' 
	throwCatchable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwCatchable" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' printMessage: 
	#' no description
	#' @return void: 
	#' 
	printMessage = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="printMessage" ); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' throwRuntime: 
	#' no description
	#' @return RCharacter: 
	#' 
	throwRuntime = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwRuntime" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	#' @description The output of toString() of this MoreFeatureTest
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this MoreFeatureTest
	#' @param object The R6 instance to test for equality to this MoreFeatureTest  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/MoreFeatureTest")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
