# Generated by r6-geenrator-maven-plugin: do not edit by hand
# This is a class of the testRapi generated R library.
#
# A test library
# Version: 0.01
# Generated: 2020-11-03T21:33:22.936
# Contact: rc538@exeter.ac.uk
MoreFeatureTest = R6::R6Class("MoreFeatureTest", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	testLogging = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="testLogging" ); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	throwCatchable = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwCatchable" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	printMessage = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="printMessage" ); 
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	throwRuntime = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacter;", method="throwRuntime" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RCharacter(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	}
))
