# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the testRapi generated R library.
#
# A test library
# Version: 0.02
# Generated: 2021-12-22T09:44:13.622
# Contact: rc538@exeter.ac.uk
Serialiser = R6::R6Class("Serialiser", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/Serialiser")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
