# Generated by maven-r-jsr223-plugin: do not edit by hand

# This loads the 
.onLoad <- function(libname, pkgname) {
		options(java.parameters = c(""))
	# pass in debug options
	.jinit(parameters=c(getOption("java.parameters"),"-Xdebug","-Xrunjdwp:transport=dt_socket,address=8998,server=y,suspend=n"), silent = FALSE, force.init = TRUE)
	message("java debugging initialised on port 8998")
	
    classes <- system.file("java", package = pkgname, lib.loc = libname)
    if (nchar(classes)) {
        .jaddClassPath(classes)
        jars <- grep(".*\\.jar", list.files(classes, full.names = TRUE), TRUE, value = TRUE)
        message(paste0("Adding to classpath: ",jars,collapse='\n'))
        .jaddClassPath(jars)
    }
    
    
}
