---
title: "R6-generator-datatypes"
author: "Rob Challen"
date: "19/10/2020"
output: html_document
header-includes:
  \usepackage{amsmath}
  \usepackage{minted}
  \usemintedstyle{emacs}
  \setminted[java]{fontsize=\footnotesize,tabsize=3}
  \setminted[xml]{fontsize=\footnotesize,tabsize=3}
---

# Datatype conversion

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("./codeSnip.R")
```

## Round tripping data from R to Java to R

```{r results='asis'}
codeSnip("java",filename="/home/terminological/Git/r6-generator-maven-plugin-test/src/main/java/uk/co/terminological/rjava/test/BounceTest.java",19) #,35,51)
```

### Nulls and voids

```{r}
devtools::install("~/Git/r6-generator-maven-plugin-test/r-library/")
library(testRapi)
J = testRapi::JavaApi$new()
b = J$BounceTest$new()

b$bounceNull(NULL)
b$bounceVoid()
```

### Character data

```{r}
b$bounceString("Hello")
b$bounceCharacter("Hello")
b$bounceCharacterVector(c("Hello","World"))
```

### Numeric data

```{r}
b$bounceDouble(1.23)
b$bounceNumeric(4.6)
b$bounceNumeric(NA_real_)
b$bounceNumeric(Inf)
b$bounceNumeric(-Inf)
b$bounceNumeric(0/0)
b$bounceNumericVector(c(2.3,4.6,34))
b$bounceNumericVector(c(2.3,4.6,NA_real_,34,NaN,Inf,-Inf))

```

### Integer data

```{r}
b$bounceInt(1)
b$bounceInteger(3)
b$bounceIntegerVector(c(2L,3L,4L))
b$bounceIntegerVector(c(2,3,4))
b$bounceIntegerVector(c(2L,NA,4L))
```

### Factors

```{r}
factorVec = as.factor(c("a","b","c","b","a"))
b$bounceFactor(as.factor(factorVec[[1]]))
b$bounceFactorVector(factorVec)
```

### Dates

```{r}
b$bounceDate(as.Date("2001-02-03"))
class(b$bounceDate(as.Date("2001-02-03")))
b$bounceDateVector(as.Date(c("2001-02-03","2001-02-04","2001-02-05")))
b$bounceDateVector(as.Date(c("2001-02-03",NA,"2001-02-05")))
```

### Logicals

```{r}
b$bounceLogical(TRUE)
b$bounceLogicalVector(c(TRUE,TRUE,FALSE))
b$bounceLogicalVector(c(TRUE,NA,FALSE))
```


### Dataframes

```{r}
b$bounceDataframe(tibble::tibble(
  x=c(0,1,2),
  y=c(3L,2L,1L)
))

b$bounceDataframe(tibble::tibble(
  u=factorVec[1:3],
  v=c(TRUE,NA,FALSE),
  w=c("alpha",NA,"gamma"),
  x=c(0,1,2),
  y=c(3L,2L,1L),
  z=as.Date(c("2001-02-03",NA,"2001-02-05"))
))
```

### Lists

```{r}
b$bounceList(list("a","b","c",c(1,2,3)))

input = list("a",list("b",1,"z"),"c",c(1,2,3))
output = b$bounceList(input)
if (!identical(input,output)) stop("FAIL")

b$bounceNamedList(list(x="a",b=c("a",NA,"c"),c=1))
```

## Generating data in Java

### Primitive equivalents

```{r results='asis'}
codeSnip("java",filename="/home/terminological/Git/r6-generator-maven-plugin-test/src/main/java/uk/co/terminological/rjava/test/FactoryTest.java",24,51) #,35,51)
```


```{r}
g = J$FactoryTest$new()

g$generateCharacter()
g$generateNumeric()
g$generateInteger()
g$generateFactor()
g$generateLogical()
```

### Vectors

```{r results='asis'}
codeSnip("java",filename="/home/terminological/Git/r6-generator-maven-plugin-test/src/main/java/uk/co/terminological/rjava/test/FactoryTest.java",53,76) #,35,51)
```

```{r}
g$generateFactorVec()
g$generateIntegerVec() 
g$generateCharacterVec()
g$generateNumericVec()
g$generateLogicalVec()
```

### Dataframes and lists

```{r results='asis'}
codeSnip("java",filename="/home/terminological/Git/r6-generator-maven-plugin-test/src/main/java/uk/co/terminological/rjava/test/FactoryTest.java",78,112) #,35,51)
```


```{r}
g$generateDataframe()
g$generateStreamDataframe()
```

```{r}
g$generateList()
g$generateNamedList()
```