# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a AnotherTestRApi java class in a jsr223 engine
JAnotherTestRApi = R6::R6Class("JAnotherTestRApi", public=list( 
	api = NULL,
	#### constructor ----
	initialize = function(message1, message2) {
		class.path <- c(
	  		system.file("java", "groovy-all-2.4.17.jar", package="testRapi"),
	  		system.file("java", "maven-r-jsr223-plugin-test-1.0-SNAPSHOT-jar-with-dependencies.jar", package="testRapi")
		)	
		self$api = jsr223::ScriptEngine$new("groovy", class.path)
		self$api$setDataFrameRowMajor(FALSE)
		self$api$tmp_message1 = message1;
		self$api$tmp_message2 = message2;
		self$api %@% '
			import uk.co.terminological.mavenrjsr233plugintest.AnotherTestRApi;
			x = new AnotherTestRApi(tmp_message1, tmp_message2);
		'
		self$api$remove("tmp_message1")
		self$api$remove("tmp_message2")
	},

	#### method: throwCatchable ----
	# returns: java.lang.String
	throwCatchable = function() {
		return(self$api$invokeMethod("x", "throwCatchable"))
	},

	#### method: printMessage ----
	# returns: void
	printMessage = function() {
		return(self$api$invokeMethod("x", "printMessage"))
	},

	#### method: throwRuntime ----
	# returns: java.lang.String
	throwRuntime = function() {
		return(self$api$invokeMethod("x", "throwRuntime"))
	},

	print = function() {
		return(self$api$invokeMethod("x", "toString"));
	}
))
