# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a java class in a jsr223 engine
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	.engine = NULL,
	.objId = 0,
	TestRApi = NULL,
	AnotherTestRApi = NULL,
  
 	#### constructor ----
 	initialize = function() {
	
	# initialise java engine
	
	class.path <- c(
		system.file("java", "groovy-all-2.4.17.jar", package="testRapi"),
		system.file("java", "r-jsr223-maven-plugin-test-1.0-SNAPSHOT-jar-with-dependencies.jar", package="testRapi")
	)	
	self$.engine = jsr223::ScriptEngine$new("groovy", class.path)
	self$.engine$setDataFrameRowMajor(FALSE)
	# set up engine
	self$.engine %@% '
		objs = [];
		nextObjId = 0;
	'
	
	# initialise constructor and static class definitions
	self$TestRApi = list(
		new = function() {
			# constructor
			# copy parameters
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = new uk.co.terminological.mavenrjsr233plugintest.TestRApi();
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# delete parameters
			return(TestRApi$new(self$.engine, objId))
		}	
	)
	self$AnotherTestRApi = list(
		new = function(message1, message2) {
			# constructor
			# copy parameters
			self$.engine$tmp_message1 = message1;
			self$.engine$tmp_message2 = message2;
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = new uk.co.terminological.mavenrjsr233plugintest.AnotherTestRApi(tmp_message1, tmp_message2);
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# delete parameters
			self$.engine$remove("tmp_message1")
			self$.engine$remove("tmp_message2")
			return(AnotherTestRApi$new(self$.engine, objId))
		}	,
		create = function(message1, message2) {
			# copy parameters
			self$.engine$tmp_message1 = message1;
			self$.engine$tmp_message2 = message2;
			#execute static call
			# execute static method and return pointer to create objId   
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = uk.co.terminological.mavenrjsr233plugintest.AnotherTestRApi.create(tmp_message1, tmp_message2);
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# wrap resulting id in R class
			out = AnotherTestRApi$new(self$.engine, objId)
			# delete parameters
			self$.engine$remove("tmp_message1")
			self$.engine$remove("tmp_message2")
			return(out)
		},
		concat = function(message1, message2) {
			# copy parameters
			self$.engine$tmp_message1 = message1;
			self$.engine$tmp_message2 = message2;
			#execute static call
			# execute static method
			out = self$.engine %~% '
				return uk.co.terminological.mavenrjsr233plugintest.AnotherTestRApi.concat(tmp_message1, tmp_message2);
			'
			# delete parameters
			self$.engine$remove("tmp_message1")
			self$.engine$remove("tmp_message2")
			return(out)
		}	)
	}
  
  
))

TestRApi = R6::R6Class("TestRApi", public=list(
	.engine = NULL,
	.objId = NULL,
	initialize = function(engine,objectId){
		self$.engine = engine;
		self$.objId = objectId;
	},
	doHelloWorld = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].doHelloWorld();
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		return(out)
	},
	fluentSetMessage = function(message) {
		# copy parameters
		self$.engine$tmp_message = message;
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returninf a new objId   
		objId = self$.engine %~% '
			synchronized(objs) {
				objs[nextObjId] = objs[tmp2_objId].fluentSetMessage(tmp_message);
				nextObjId = nextObjId+1 
			}
			return nextObjId-1;
		'
		# wrap resulting id in R class
		out = TestRApi$new(self$.engine, objId)
		# delete parameters
		self$.engine$remove("tmp2_objId")
		self$.engine$remove("tmp_message")
		return(out)
	},
	factoryMethod = function(a, b) {
		# copy parameters
		self$.engine$tmp_a = a;
		self$.engine$tmp_b = b;
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returninf a new objId   
		objId = self$.engine %~% '
			synchronized(objs) {
				objs[nextObjId] = objs[tmp2_objId].factoryMethod(tmp_a, tmp_b);
				nextObjId = nextObjId+1 
			}
			return nextObjId-1;
		'
		# wrap resulting id in R class
		out = AnotherTestRApi$new(self$.engine, objId)
		# delete parameters
		self$.engine$remove("tmp2_objId")
		self$.engine$remove("tmp_a")
		self$.engine$remove("tmp_b")
		return(out)
	},
	getMessage = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].getMessage();
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		return(out)
	},
	doSum = function(a, b) {
		# copy parameters
		self$.engine$tmp_a = a;
		self$.engine$tmp_b = b;
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].doSum(tmp_a, tmp_b);
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		self$.engine$remove("tmp_a")
		self$.engine$remove("tmp_b")
		return(out)
	},
	print = function() {
		self$.engine$tmp2_objId = self$.objId;
		out = self$.engine %~% '
			return objs[tmp2_objId].toString();
		'
		self$.engine$remove("tmp2_objId")
		return(out)
	}
))

AnotherTestRApi = R6::R6Class("AnotherTestRApi", public=list(
	.engine = NULL,
	.objId = NULL,
	initialize = function(engine,objectId){
		self$.engine = engine;
		self$.objId = objectId;
	},
	throwCatchable = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].throwCatchable();
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		return(out)
	},
	printMessage = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].printMessage();
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		invisible(NULL)
	},
	throwRuntime = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].throwRuntime();
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		return(out)
	},
	print = function() {
		self$.engine$tmp2_objId = self$.objId;
		out = self$.engine %~% '
			return objs[tmp2_objId].toString();
		'
		self$.engine$remove("tmp2_objId")
		return(out)
	}
))

