# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a TestRApi java class in a jsr223 engine
JTestRApi = R6::R6Class("JTestRApi", public=list( 
	api = NULL,
	#### constructor ----
	initialize = function() {
		class.path <- c(
	  		system.file("java", "groovy-all-2.4.17.jar", package="testRapi"),
	  		system.file("java", "maven-r-jsr223-plugin-test-1.0-SNAPSHOT-jar-with-dependencies.jar", package="testRapi")
		)	
		self$api = jsr223::ScriptEngine$new("groovy", class.path)
		self$api$setDataFrameRowMajor(FALSE)
		self$api %@% '
			import uk.co.terminological.mavenrjsr233plugintest.TestRApi;
			x = new TestRApi();
		'
	},

	#### method: doHelloWorld ----
	# returns: java.lang.String
	doHelloWorld = function() {
		return(self$api$invokeMethod("x", "doHelloWorld"))
	},

	#### method: fluentSetMessage ----
	# returns: uk.co.terminological.mavenrjsr233plugintest.TestRApi
	fluentSetMessage = function(message) {
		self$api$tmp_message = message;
		self$api %@% 'x = x.fluentSetMessage(tmp_message);';
		self$api$remove("tmp_message")
		invisible(self);
	},

	#### method: getMessage ----
	# returns: java.lang.String
	getMessage = function() {
		return(self$api$invokeMethod("x", "getMessage"))
	},

	#### method: doSum ----
	# returns: java.lang.Double
	doSum = function(a, b) {
		return(self$api$invokeMethod("x", "doSum", a, b))
	},

	print = function() {
		return(self$api$invokeMethod("x", "toString"));
	}
))
